// Configs des skins T2–T7 : tokens reproduisant l'identité de chaque design
// du zip Claude Design. Les couleurs d'accent passent par var(--ff-accent, X)
// pour rester éditables ; le reste reprend la palette exacte du zip.

import type { SkinTokens } from "./factory";

/* ─── T2 · E-book Corporate Mixte (lead-snap) — light navy/orange/teal ─── */
export const T2_TOKENS: SkinTokens = {
  id: "lead-snap",
  dark: false,
  accent: "var(--ff-accent, #F58A1E)",
  accent2: "var(--ff-accent2, #2EC4B6)",
  accentSoft: "#FBBF77",
  ink: "#0B1D3A",
  body: "#374151",
  muted: "#6B7280",
  grad: "linear-gradient(100deg, var(--ff-accent, #F58A1E), #2EC4B6)",
  cardBg: "#ffffff",
  cardBorder: "#EDF0F2",
  cardShadow: "0 2px 12px rgba(0,0,0,.06)",
  cardRadius: 12,
  chipBg: "#E7F6F4",
  chipInk: "#0F766E",
  chipRadius: 5,
  btnRadius: 5,
  btnUppercase: true,
  headFont: "'DM Sans', system-ui, sans-serif",
  headWeight: 700,
  h1Size: "clamp(32px, 4.6cqw, 44px)",
  h2Size: "clamp(26px, 3.8cqw, 36px)",
  heroVariant: "split",
  heroMedia: "book",
  numberVariant: "circle",
  quoteBig: true,
  faqBg: "#F8F9FA",
  faqBorder: "#E5E7EB",
  ctaPanelBg: "#0B1D3A",
  ctaPanelInk: "#ffffff",
  ctaPanelSub: "#B9C4D4",
  urgencyBg: "#0B1D3A",
  urgencyBlockBg: "rgba(255,255,255,.06)",
  urgencyBlockBorder: "rgba(255,255,255,.14)",
  urgencyNumInk: "#ffffff",
  urgencyLabelInk: "#2EC4B6",
};

/* ─── T3 · Événement Dark Mystérieux (story-sell) — dark magenta/violet ── */
export const T3_TOKENS: SkinTokens = {
  id: "story-sell",
  dark: true,
  accent: "var(--ff-accent, #FF007F)",
  accent2: "var(--ff-accent2, #7B1FA2)",
  accentSoft: "#FF6BB0",
  ink: "#ffffff",
  body: "#ADADAD",
  muted: "#8A8A8A",
  grad: "linear-gradient(100deg, var(--ff-accent, #FF007F), #7B1FA2)",
  cardBg: "rgba(255,255,255,.04)",
  cardBorder: "rgba(255,255,255,.1)",
  cardGlass: true,
  cardEdgeLeft: true,
  cardTilt: true,
  cardRadius: 14,
  chipBg: "rgba(255,0,127,.1)",
  chipInk: "#FF6BB0",
  chipRadius: 30,
  btnRadius: 34,
  headFont: "'Space Grotesk', system-ui, sans-serif",
  headWeight: 700,
  headTransform: "uppercase",
  headTracking: ".02em",
  h1Size: "clamp(38px, 6.4cqw, 64px)",
  h2Size: "clamp(27px, 4cqw, 38px)",
  heroVariant: "centered",
  heroMedia: "plain",
  numberVariant: "chip-grad",
  priceColor: "var(--ff-accent3, #FFD700)",
  faqBg: "#1A1A1A",
  faqBorder: "rgba(255,255,255,.08)",
  ctaPanelBg: "linear-gradient(120deg, #24101c, #1a0d24)",
  ctaPanelInk: "#ffffff",
  ctaPanelSub: "#ADADAD",
  urgencyBg: "linear-gradient(120deg, #24101c, #1a0d24)",
  urgencyBlockBg: "rgba(255,255,255,.04)",
  urgencyBlockBorder: "rgba(255,255,255,.1)",
  urgencyNumInk: "#ffffff",
  urgencyLabelInk: "#C77BE0",
};

/* ─── T4 · Coach Service Light (clean-light) — light teal, Fraunces ────── */
export const T4_TOKENS: SkinTokens = {
  id: "clean-light",
  dark: false,
  accent: "var(--ff-accent, #1D4A4A)",
  accent2: "var(--ff-accent2, #0F766E)",
  accentSoft: "#BFE3DD",
  ink: "#1D4A4A",
  body: "#4B5563",
  muted: "#6B7280",
  grad: "linear-gradient(100deg, var(--ff-accent, #1D4A4A), #0F766E)",
  cardBg: "#ffffff",
  cardBorder: "#E5E7EB",
  cardShadow: "0 4px 16px rgba(29,74,74,.08)",
  cardRadius: 12,
  chipBg: "#E6F0F0",
  chipInk: "#1D4A4A",
  chipRadius: 8,
  btnRadius: 8,
  headFont: "'Fraunces', serif",
  headWeight: 600,
  headTracking: "-.01em",
  h1Size: "clamp(34px, 4.8cqw, 46px)",
  h2Size: "clamp(26px, 3.7cqw, 36px)",
  heroVariant: "split",
  heroMedia: "plain",
  headAlign: "left",
  numberVariant: "editorial",
  processRows: true,
  quoteBig: true,
  faqBg: "#F8F9FA",
  faqBorder: "#E5E7EB",
  ctaPanelBg: "#1D4A4A",
  ctaPanelInk: "#ffffff",
  ctaPanelSub: "#BFE3DD",
  urgencyBg: "#E6F0F0",
  urgencyBlockBg: "#ffffff",
  urgencyBlockBorder: "#E5E7EB",
  urgencyNumInk: "#1D4A4A",
  urgencyLabelInk: "#0F766E",
};

/* ─── T5 · SaaS Light Blue (premium-minimal) — light blue, Montserrat ──── */
export const T5_TOKENS: SkinTokens = {
  id: "premium-minimal",
  dark: false,
  accent: "var(--ff-accent, #2563EB)",
  accent2: "var(--ff-accent2, #1D4ED8)",
  accentSoft: "#93B4FB",
  ink: "#111827",
  body: "#4B5563",
  muted: "#6B7280",
  grad: "linear-gradient(100deg, var(--ff-accent, #2563EB), #1D4ED8)",
  cardBg: "#ffffff",
  cardBorder: "#EEF1F5",
  cardShadow: "0 4px 18px rgba(17,24,39,.05)",
  cardRadius: 12,
  cardTilt: true,
  chipBg: "#EFF4FF",
  chipInk: "#1D4ED8",
  chipRadius: 50,
  btnRadius: 50,
  headFont: "'Montserrat', system-ui, sans-serif",
  headWeight: 800,
  h1Size: "clamp(34px, 5cqw, 48px)",
  h2Size: "clamp(27px, 4cqw, 38px)",
  heroVariant: "split",
  heroMedia: "browser",
  numberVariant: "circle",
  faqBg: "#F9FAFB",
  faqBorder: "#E5E7EB",
  ctaPanelBg: "#111827",
  ctaPanelInk: "#ffffff",
  ctaPanelSub: "#D1D5DB",
  urgencyBg: "#EFF4FF",
  urgencyBlockBg: "#ffffff",
  urgencyBlockBorder: "#DCE6FB",
  urgencyNumInk: "#111827",
  urgencyLabelInk: "#2563EB",
};

/* ─── T6 · Agence B2B Teal (trust-pro) — light gray/teal/ambre, Inter ──── */
export const T6_TOKENS: SkinTokens = {
  id: "trust-pro",
  dark: false,
  accent: "var(--ff-accent, #0D9488)",
  accent2: "var(--ff-accent2, #F59E0B)",
  accentSoft: "#CFF3EF",
  ink: "#1F2937",
  body: "#4B5563",
  muted: "#6B7280",
  grad: "linear-gradient(100deg, var(--ff-accent, #0D9488), #14B8A6)",
  cardBg: "#ffffff",
  cardBorder: "#EEF1F5",
  cardShadow: "0 2px 10px rgba(17,24,39,.05)",
  cardRadius: 12,
  chipBg: "#E7F6F4",
  chipInk: "#0D7A70",
  chipRadius: 8,
  btnRadius: 8,
  headFont: "'Inter', system-ui, sans-serif",
  headWeight: 700,
  h1Size: "clamp(32px, 4.6cqw, 44px)",
  h2Size: "clamp(25px, 3.6cqw, 34px)",
  heroVariant: "centered",
  heroMedia: "plain",
  headAlign: "left",
  numberVariant: "editorial",
  processRows: true,
  quoteBig: true,
  priceColor: "var(--ff-accent3, #F59E0B)",
  faqBg: "#F9FAFB",
  faqBorder: "#E5E7EB",
  ctaPanelBg: "#1F2937",
  ctaPanelInk: "#ffffff",
  ctaPanelSub: "#D1D5DB",
  urgencyBg: "#F9FAFB",
  urgencyBlockBg: "#ffffff",
  urgencyBlockBorder: "#E5E7EB",
  urgencyNumInk: "#1F2937",
  urgencyLabelInk: "#0D9488",
};

/* ─── T7 · Fitness Dark Energy (bold-energy) — blanc/noir/rouge, Bebas ─── */
export const T7_TOKENS: SkinTokens = {
  id: "bold-energy",
  dark: false,
  accent: "var(--ff-accent, #EF4444)",
  accent2: "var(--ff-accent2, #F97316)",
  accentSoft: "#FACC15",
  ink: "#000000",
  body: "#4B4B4B",
  muted: "#6B6B6B",
  grad: "linear-gradient(100deg, var(--ff-accent, #EF4444), #F97316)",
  cardBg: "#ffffff",
  cardBorder: "#000000",
  cardBorderWidth: 2,
  cardRadius: 8,
  chipBg: "#000000",
  chipInk: "#FACC15",
  chipRadius: 4,
  btnRadius: 4,
  btnUppercase: true,
  headFont: "'Bebas Neue', 'Archivo Black', sans-serif",
  headWeight: 400,
  headTransform: "uppercase",
  headTracking: ".04em",
  h1Size: "clamp(46px, 8cqw, 76px)",
  h2Size: "clamp(34px, 5.4cqw, 52px)",
  heroVariant: "centered",
  heroMedia: "plain",
  numberVariant: "circle",
  priceColor: "var(--ff-accent3, var(--ff-accent, #EF4444))",
  faqBg: "#ffffff",
  faqBorder: "#000000",
  ctaPanelBg: "#000000",
  ctaPanelInk: "#ffffff",
  ctaPanelSub: "#9A9A9A",
  urgencyBg: "#000000",
  urgencyBlockBg: "rgba(255,255,255,.06)",
  urgencyBlockBorder: "rgba(255,255,255,.18)",
  urgencyNumInk: "#FACC15",
  urgencyLabelInk: "#ffffff",
};
